Repository Suchica/workstats, pull requests merged in 2022-04, with the labels that each got.

#34 Display user collection data on the user settings screen according to…
  components/Avatar.tsx
  components/InputBox.tsx
  config/firebaseTypes.ts
  firebaseAdmin.ts
  pages/user-settings.tsx
Labels: enhancement

#37 Added github actions to check whether the app can be build or not
  .github/workflows/AppBuilds.yml
  .github/workflows/github-actions-demo.yml
Labels: enhancement, High

#36 Resolved and avoided build errors according to Linting rules.
  .eslintrc.js
  auth.tsx
  components/Avatar.tsx
  components/Layout.tsx
  components/ProfileList.tsx
  components/boxes/InputBox.tsx
  components/buttons/ButtonList.tsx
  components/buttons/SpecifyPeriodFromTo.tsx
  components/buttons/SpecifyPeriodLastWeek.tsx
  components/buttons/SubmitButton.tsx
  components/cards/Auth&SignInButton.tsx
  components/cards/CardList.tsx
  components/cards/NumberOfCloseTasks.tsx
  components/cards/NumberOfCommits.tsx
  components/cards/NumberOfMentioned.tsx
  components/cards/NumberOfMtgs.tsx
  components/cards/NumberOfNewSent.tsx
  components/cards/NumberOfOpenTasks.tsx
  components/cards/NumberOfPullRequests.tsx
  components/cards/NumberOfReplies.tsx
  components/cards/NumberOfReview.tsx
  components/cards/TotalTimeOfMtgs.tsx
  components/charts/RadarChart.tsx
  components/common/Footer.tsx
  components/common/Loading.tsx
  components/common/Login.tsx
  components/common/Sidebar.tsx
  components/common/Topbar.tsx
  config/firebaseClient.js
  config/firebaseTypes.ts
  firebaseAdmin.ts
  jest.config.js
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  pages/privacy-policy.tsx
  pages/terms-of-service.tsx
  pages/user-list.tsx
  pages/user-settings.tsx
  postcss.config.js
  prettier.config.js
  services/asanaServices.client.tsx
  services/getAUserDocFromFirebase.tsx
  services/getAnImageFromStorage.tsx
  services/githubServices.client.tsx
  services/googleCalendar.client.tsx
  services/slackServices.server.tsx
  tailwind.config.js
Labels: bug, linting

#39 Added form submit functions to store user info in firestore from User-settings page
  components/boxes/InputBox.tsx
  components/buttons/SubmitButton.tsx
  config/firebaseClient.js
  config/firebaseTypes.ts
  pages/user-settings.tsx
  services/githubServices.client.tsx
  services/setUserDocToFirestore.tsx
Labels: enhancement

#40 Added a few comments to the code.
  README.md
  services/githubServices.client.tsx
  services/setUserDocToFirestore.tsx
Labels: linting
