Repository Suchica/workstats, pull requests merged in 2022-05, with the labels that each got.

#41 Added a logout button on every page and improved the look of the login page.
  components/Layout.tsx
  components/common/Login.tsx
  components/common/Logout.tsx
  config/firebaseClient.js
  pages/_app.tsx
  pages/index.tsx
  public/asana-svgrepo-com.svg
  public/github-svgrepo-com.svg
  public/google-calendar-svgrepo-com.svg
  public/slack-svgrepo-com.svg
Labels: bug, enhancement

#42 Resolved firebase auth error: auth/account-exists-with-different-credential
  components/common/Login.tsx
  components/common/Logout.tsx
Labels: bug, enhancement

#43 Resolved firebase error: auth/id-token-expired every 1 hour in getServerSideProps
  auth.tsx
  components/common/Login.tsx
  pages/index.tsx
Labels: bug, enhancement

#45 Creates a user doc without any field when a user signed in if the doc doesn't exist.
  .github/pull_request_template.md
  components/common/Login.tsx
  pages/login.tsx
  services/asanaServices.client.tsx
  services/setUserDocToFirestore.tsx
Labels: enhancement

#46 Added Terms of Service and Privacy Policy using those generators
  components/common/Login.tsx
  components/common/Logout.tsx
  components/common/Sidebar.tsx
  pages/privacy-policy.tsx
  pages/terms-of-service.tsx
  pages/user-settings.tsx
Labels: documentation, enhancement

#47 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, enhancement

#48 Added a help page and its link buttons to set up GitHub info in user settings page.
  .github/pull_request_template.md
  components/cards/CardList.tsx
  components/cards/TotalTimeOfMtgs.tsx
  components/common/Avatar.tsx
  components/common/GearIcon.tsx
  components/common/Layout.tsx
  components/common/Logout.tsx
  components/common/ProfileList.tsx
  components/common/QuestionMark.tsx
  pages/_app.tsx
  pages/help/how-to-get-github-info.tsx
  pages/index.tsx
  pages/privacy-policy.tsx
  pages/terms-of-service.tsx
  pages/user-list.tsx
  pages/user-settings.tsx
  public/asana-svgrepo-com.svg
  public/gear-svgrepo-com.svg
  public/help/Chrome_RequestGitHubAPI.png
  public/help/Chrome_ResponseGitHubAPI.png
  public/help/Dashboard_GitHubAggregated.png
  public/help/Dashboard_GoToUserSettings.png
  public/help/Dashboard_InitialState.png
  public/help/Dashboard_NoRedMark.png
  public/help/GitHub_RepoTop.png
  public/help/GitHub_RepoVisibility.png
  public/help/GitHub_TopPage.png
  public/help/GitHub_UserName.png
  public/help/Top_Login.png
  public/help/UserSettings_GitHubInfo.png
  public/help/UserSettings_GitHubInfoFulfilled.png
  public/help/UserSettings_GoToHome.png
  public/help/UserSettings_NoRedMark.png
  public/noImageWith16-9.png
Labels: documentation, enhancement

#50 Added a help page to set up Asana info
  components/cards/CardList.tsx
  components/common/GearIcon.tsx
  pages/help/how-to-get-asana-info.tsx
  pages/help/how-to-get-github-info.tsx
  pages/user-settings.tsx
  public/help/Asana_DeveloperConsole.png
  public/help/Asana_DeveloperConsole_CreateToken.png
  public/help/Asana_MySettings.png
  public/help/Asana_MySettingsWithRed.png
  public/help/Chrome_AsanaTop.png
  public/help/Chrome_AsanaTopWithRed&ZoomUp.png
  public/help/Chrome_AsanaTopWithRed.png
  public/help/Chrome_RequestAsanaAPI.png
  public/help/Chrome_ResponseAsanaAPI.png
  public/help/Chrome_ResponseAsanaWorkspaceAPI.png
  public/help/Chrome_ResponseAsanaWorkspaceAPIWithRed.png
  public/help/Chrome_ResponseAsanaWorkspaceAPIWithRed1.png
  public/help/Chrome_ResponseAsanaWorkspaceAPIWithRed2.png
  public/help/Dashboard_AsanaAggregated.png
  public/help/Dashboard_AsanaAggregatedWithRed.png
  public/help/Dashboard_Asana_InitialState.png
  public/help/Dashboard_GitHub_InitialState.png
  public/help/Dashboard_GoToUserSettings_Asana.png
  public/help/Dashboard_NoRedMark.png
  public/help/UserSettings_AsanaInfo.png
  public/help/UserSettings_AsanaInfoFulfilled.png
  public/help/UserSettings_NoRedMark2.png
Labels: bug, documentation, enhancement

#51 Added console.log to examine an error which occurs only in production environment.
  components/common/Login.tsx
  firebaseAdmin.ts
  package.json
Labels: bug

#52 Disabled a function to specify period of terms for production env
  components/buttons/ButtonList.tsx
  components/buttons/SpecifyPeriodFixedTerm.tsx
  components/buttons/SpecifyPeriodFromTo.tsx
  components/buttons/SpecifyPeriodLastWeek.tsx
  components/cards/NumberOfPullRequests.tsx
Labels: bug

#54 Resolved npm error for dependencies of dependencies
  auth.tsx
  package-lock.json
  package.json
  pages/terms-of-service.tsx
  services/githubServices.client.tsx
Labels: bug, enhancement

#56 Added auto generated sitemap.xml and robots.txt at build
  package-lock.json
  package.json
  sitemap.config.js
Labels: documentation, enhancement

#57 Resolved mis-configuration for sitemap location
  package.json
  public/robots.txt
  public/sitemap-0.xml
  public/sitemap.xml
  sitemap.config.js
Labels: bug

#59 Added "Connect with GitHub" button to use GitHub access token on behalf of users and viceversa
  components/boxes/InputBox.tsx
  components/buttons/ConnectWithGithub.tsx
  components/buttons/DisconnectWithGithubButton.tsx
  components/buttons/SubmitButton.tsx
  components/cards/NumberOfCommits.tsx
  components/common/Logout.tsx
  config/firebaseTypes.ts
  pages/api/get-github-access-token.ts
  pages/index.tsx
  pages/user-settings.tsx
  public/sitemap-0.xml
  services/githubServices.client.tsx
  services/setDocToFirestore.tsx
Labels: enhancement

#60 Enabled GitHub APIs to access private repositories
  components/cards/CardList.tsx
  components/cards/NumberOfCommits.tsx
  components/cards/NumberOfPullRequests.tsx
  components/cards/NumberOfReview.tsx
  pages/index.tsx
  pages/user-settings.tsx
  public/sitemap-0.xml
  services/githubServices.client.tsx
Labels: enhancement
