Repository Suchica/workstats, pull requests merged in 2022-07, with the labels that each got.

#86 Changed to store aggregated GitHub numbers in Firestore and display those values on first render
  .github/pull_request_template.md
  .gitignore
  components/cards/CardList.tsx
  components/cards/NumberOfCommits.tsx
  components/cards/NumberOfPullRequests.tsx
  components/cards/NumberOfReview.tsx
  config/firebaseTypes.ts
  pages/cancel-membership.tsx
  pages/index.tsx
  pages/user-settings.tsx
  services/getDocFromFirestore.ts
  services/githubServices.client.tsx
  services/setDocToFirestore.tsx
Labels: enhancement

#87 Hotfilx: Fixed a bug that the numbers were once set to 0 when the Asana API access token expired after 1 hour.
  components/cards/CardList.tsx
  services/asanaServices.client.tsx
Labels: bug

#88 Hotfix: Fixed a bug that caused an error for new users due to a new table.
  components/cards/CardList.tsx
  components/common/Login.tsx
  pages/index.tsx
  services/setDocToFirestore.tsx
Labels: bug

#92 Added Google Calendar OAuth 2.0 support and its Number of Events aggregation
  .github/pull_request_template.md
  auth.tsx
  components/buttons/DisconnectWithGoogleButton.tsx
  components/buttons/DisconnectWithSlackButton.tsx
  components/buttons/SpecifyPeriodFromTo.tsx
  components/cards/Auth&SignInButton.tsx
  components/cards/CardList.tsx
  components/cards/TotalTimeOfMtgs.tsx
  config/firebaseTypes.ts
  pages/api/google-calendar/get-access-token.ts
  pages/api/google-calendar/get-number-of-events.ts
  pages/api/revoke-google-refresh-token.ts
  pages/index.tsx
  pages/user-settings.tsx
  services/googleCalendar.client.tsx
  services/setDocToFirestore.tsx
Labels: enhancement

#89 feature: Global State with Context API for data Timeframes
  components/buttons/ButtonList.tsx
  components/buttons/SpecifyPeriodFixedTerm.tsx
  constants/timestampButtonList.json
  context/GlobalContextProvider.tsx
  pages/_app.tsx
Labels: enhancement

#94 Added how to use your data from Google Calendar API in the Privacy Policy page
  pages/privacy-policy.tsx
Labels: enhancement

#95 Revised how to use Google Calendar data in privacy-policy page
  pages/privacy-policy.tsx
Labels: documentation

#96 Revert "Revert "Added Google Calendar OAuth 2.0 support and its Number of Events aggregation""
  .github/pull_request_template.md
  auth.tsx
  components/buttons/DisconnectWithGoogleButton.tsx
  components/buttons/DisconnectWithSlackButton.tsx
  components/buttons/SpecifyPeriodFromTo.tsx
  components/cards/Auth&SignInButton.tsx
  components/cards/CardList.tsx
  components/cards/TotalTimeOfMtgs.tsx
  config/firebaseTypes.ts
  pages/api/google-calendar/get-access-token.ts
  pages/api/google-calendar/get-number-of-events.ts
  pages/api/revoke-google-refresh-token.ts
  pages/index.tsx
  pages/user-settings.tsx
  services/googleCalendar.client.tsx
  services/setDocToFirestore.tsx
Labels: enhancement
